// Données statiques des 12 recettes italiennes
const recettes = [
  {
    id: 1,
    slug: "risotto-al-tartufo",
    nom: "Risotto al Tartufo",
    categorie: "primo",
    difficulte: "moyen",
    temps: 40,
    portions: 4,
    description: "Un risotto crémeux au truffe noire, symbole de la gastronomie italienne d'exception.",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80",
    ingredients: [
      "320g de riz Arborio",
      "1 truffe noire (20g)",
      "1,2L de bouillon de légumes chaud",
      "1 oignon",
      "120ml de vin blanc sec",
      "60g de parmesan râpé",
      "40g de beurre",
      "2 cuillères à soupe d'huile d'olive",
      "Sel et poivre",
    ],
    etapes: [
      "Faire revenir l'oignon émincé dans l'huile d'olive jusqu'à transparence.",
      "Ajouter le riz et le faire nacrer 2 minutes en remuant.",
      "Déglacer avec le vin blanc et laisser absorber.",
      "Ajouter le bouillon chaud louche par louche en remuant constamment.",
      "Après 18 minutes, retirer du feu et incorporer le beurre et le parmesan.",
      "Râper la truffe généreusement sur le risotto et servir immédiatement.",
    ],
  },
  {
    id: 2,
    slug: "spaghetti-alla-carbonara",
    nom: "Spaghetti alla Carbonara",
    categorie: "primo",
    difficulte: "moyen",
    temps: 25,
    portions: 4,
    description: "La vraie carbonara romaine : guanciale, œufs, pecorino — sans crème.",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&q=80",
    ingredients: [
      "400g de spaghetti",
      "200g de guanciale (ou pancetta)",
      "4 jaunes d'œufs + 1 œuf entier",
      "100g de pecorino romano râpé",
      "50g de parmesan râpé",
      "Poivre noir fraîchement moulu",
      "Sel",
    ],
    etapes: [
      "Cuire les spaghetti al dente dans une grande casserole d'eau salée.",
      "Faire revenir le guanciale coupé en lardons jusqu'à ce qu'il soit croustillant.",
      "Mélanger les jaunes, l'œuf entier et les fromages râpés. Poivrer généreusement.",
      "Égoutter les pâtes en gardant l'eau de cuisson. Retirer le guanciale du feu.",
      "Ajouter les pâtes au guanciale, verser la sauce aux œufs hors du feu.",
      "Ajouter un peu d'eau de cuisson pour crémer. Servir immédiatement.",
    ],
  },
  {
    id: 3,
    slug: "tiramisu-classico",
    nom: "Tiramisù Classico",
    categorie: "dolce",
    difficulte: "facile",
    temps: 30,
    portions: 6,
    description: "Le dessert italien par excellence : mascarpone, café et biscuits savoiardi.",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&q=80",
    ingredients: [
      "500g de mascarpone",
      "4 œufs (séparés)",
      "100g de sucre",
      "300ml de café espresso refroidi",
      "200g de biscuits savoiardi (boudoirs)",
      "3 cuillères à soupe de Marsala (facultatif)",
      "Cacao en poudre non sucré",
    ],
    etapes: [
      "Battre les jaunes d'œufs avec le sucre jusqu'à obtenir un mélange blanchi.",
      "Incorporer le mascarpone en mélangeant délicatement.",
      "Battre les blancs en neige ferme et les incorporer à la crème.",
      "Tremper rapidement les savoiardi dans le café (+ Marsala si désiré).",
      "Alterner couches de biscuits et de crème dans un plat.",
      "Réfrigérer au moins 4 heures. Saupoudrer de cacao avant de servir.",
    ],
  },
  {
    id: 4,
    slug: "bruschetta-al-pomodoro",
    nom: "Bruschetta al Pomodoro",
    categorie: "antipasto",
    difficulte: "facile",
    temps: 15,
    portions: 4,
    description: "Tartines grillées à la tomate fraîche, ail et basilic — la simplicité absolue.",
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800&q=80",
    ingredients: [
      "8 tranches de pain ciabatta",
      "4 tomates mûres",
      "2 gousses d'ail",
      "Basilic frais",
      "4 cuillères à soupe d'huile d'olive extra vierge",
      "Sel et poivre",
    ],
    etapes: [
      "Griller les tranches de pain des deux côtés.",
      "Frotter immédiatement chaque tranche avec une gousse d'ail coupée.",
      "Couper les tomates en dés et assaisonner avec huile, sel et poivre.",
      "Disposer les tomates sur les tranches de pain.",
      "Garnir de feuilles de basilic frais et d'un filet d'huile d'olive.",
    ],
  },
  {
    id: 5,
    slug: "ossobuco-alla-milanese",
    nom: "Ossobuco alla Milanese",
    categorie: "secondo",
    difficulte: "difficile",
    temps: 120,
    portions: 4,
    description: "Jarret de veau braisé milanais, servi avec la traditionnelle gremolata.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    ingredients: [
      "4 tranches de jarret de veau (ossobuco)",
      "2 oignons",
      "2 carottes",
      "2 branches de céleri",
      "200ml de vin blanc",
      "400ml de bouillon de veau",
      "400g de tomates pelées",
      "Gremolata : zeste de citron, ail, persil",
      "Farine, huile d'olive, sel, poivre",
    ],
    etapes: [
      "Fariner les ossobucos et les dorer dans l'huile des deux côtés.",
      "Faire revenir les légumes émincés jusqu'à tendreté.",
      "Remettre la viande, déglacer au vin blanc.",
      "Ajouter les tomates et le bouillon. Couvrir et mijoter 1h30 à feu doux.",
      "Préparer la gremolata en mélangeant zeste de citron, ail et persil.",
      "Servir les ossobucos nappés de sauce, garnis de gremolata.",
    ],
  },
  {
    id: 6,
    slug: "pizza-margherita",
    nom: "Pizza Margherita",
    categorie: "primo",
    difficulte: "moyen",
    temps: 90,
    portions: 2,
    description: "La reine des pizzas : pâte napolitaine, San Marzano, mozzarella di bufala.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80",
    ingredients: [
      "300g de farine 00",
      "200ml d'eau tiède",
      "7g de levure de boulanger",
      "1 cuillère à café de sel",
      "200g de tomates San Marzano",
      "200g de mozzarella di bufala",
      "Basilic frais",
      "Huile d'olive extra vierge",
    ],
    etapes: [
      "Dissoudre la levure dans l'eau tiède. Mélanger avec la farine et le sel.",
      "Pétrir 10 minutes jusqu'à obtenir une pâte lisse. Laisser lever 1 heure.",
      "Étaler la pâte en disque fin de 30cm de diamètre.",
      "Étaler les tomates écrasées, parsemer de mozzarella déchirée.",
      "Cuire au four à 250°C (ou plus) pendant 8-10 minutes.",
      "Garnir de basilic frais et d'un filet d'huile d'olive à la sortie du four.",
    ],
  },
  {
    id: 7,
    slug: "vitello-tonnato",
    nom: "Vitello Tonnato",
    categorie: "antipasto",
    difficulte: "moyen",
    temps: 60,
    portions: 6,
    description: "Fines tranches de veau froid nappées d'une sauce crémeuse au thon piémontaise.",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    ingredients: [
      "800g de noix de veau",
      "160g de thon à l'huile égoutté",
      "3 anchois",
      "2 cuillères à soupe de câpres",
      "150g de mayonnaise",
      "Jus d'un demi-citron",
      "Bouillon de légumes pour la cuisson",
    ],
    etapes: [
      "Cuire le veau dans le bouillon frémissant 45 minutes. Laisser refroidir.",
      "Mixer le thon, les anchois, les câpres et le jus de citron.",
      "Incorporer la mayonnaise au mélange mixé pour une sauce lisse.",
      "Trancher finement le veau refroidi.",
      "Napper généreusement les tranches de sauce tonnato.",
      "Garnir de câpres et réfrigérer 1 heure avant de servir.",
    ],
  },
  {
    id: 8,
    slug: "panna-cotta-ai-frutti-di-bosco",
    nom: "Panna Cotta ai Frutti di Bosco",
    categorie: "dolce",
    difficulte: "facile",
    temps: 20,
    portions: 4,
    description: "Crème cuite délicate à la vanille, servie avec un coulis de fruits des bois.",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
    ingredients: [
      "500ml de crème entière",
      "50g de sucre",
      "1 gousse de vanille",
      "3 feuilles de gélatine",
      "200g de fruits des bois (framboises, myrtilles, mûres)",
      "2 cuillères à soupe de sucre pour le coulis",
    ],
    etapes: [
      "Ramollir les feuilles de gélatine dans l'eau froide.",
      "Chauffer la crème avec le sucre et les graines de vanille sans bouillir.",
      "Essorer la gélatine et la dissoudre dans la crème chaude.",
      "Verser dans des ramequins et réfrigérer au moins 4 heures.",
      "Préparer le coulis en cuisant les fruits avec le sucre 5 minutes.",
      "Démouler les panna cotta et napper de coulis.",
    ],
  },
  {
    id: 9,
    slug: "saltimbocca-alla-romana",
    nom: "Saltimbocca alla Romana",
    categorie: "secondo",
    difficulte: "facile",
    temps: 20,
    portions: 4,
    description: "Escalopes de veau à la sauge et au prosciutto, sautées au beurre et au vin blanc.",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    ingredients: [
      "8 escalopes de veau fines",
      "8 tranches de prosciutto di Parma",
      "8 feuilles de sauge fraîche",
      "100ml de vin blanc sec",
      "50g de beurre",
      "2 cuillères à soupe d'huile d'olive",
      "Sel et poivre",
    ],
    etapes: [
      "Poser une feuille de sauge sur chaque escalope, recouvrir d'une tranche de prosciutto.",
      "Fixer avec un cure-dent. Poivrer légèrement.",
      "Faire fondre le beurre avec l'huile dans une grande poêle.",
      "Saisir les escalopes côté prosciutto 2 minutes, puis retourner 1 minute.",
      "Déglacer au vin blanc et laisser réduire 1 minute.",
      "Servir immédiatement nappé du jus de cuisson.",
    ],
  },
  {
    id: 10,
    slug: "lasagne-alla-bolognese",
    nom: "Lasagne alla Bolognese",
    categorie: "primo",
    difficulte: "difficile",
    temps: 150,
    portions: 6,
    description: "Le grand classique bolognais : ragu au bœuf, béchamel et pâtes fraîches.",
    image: "https://images.unsplash.com/photo-1619895092538-128341789043?w=800&q=80",
    ingredients: [
      "500g de pâtes à lasagne",
      "500g de bœuf haché",
      "200g de pancetta",
      "400g de tomates pelées",
      "100ml de vin rouge",
      "1L de lait pour la béchamel",
      "80g de beurre, 80g de farine",
      "150g de parmesan râpé",
      "Oignon, carotte, céleri",
    ],
    etapes: [
      "Préparer le ragù : faire revenir la pancetta et les légumes, ajouter la viande.",
      "Ajouter le vin rouge, les tomates et laisser mijoter 1 heure minimum.",
      "Préparer la béchamel avec beurre, farine et lait chaud.",
      "Cuire les pâtes al dente si fraîches (pas si sèches).",
      "Alterner couches de pâtes, ragù, béchamel et parmesan.",
      "Cuire au four à 180°C pendant 40 minutes, gratiner les 5 dernières minutes.",
    ],
  },
  {
    id: 11,
    slug: "carpaccio-di-manzo",
    nom: "Carpaccio di Manzo",
    categorie: "antipasto",
    difficulte: "facile",
    temps: 15,
    portions: 4,
    description: "Fines lamelles de bœuf cru à l'huile d'olive, citron et copeaux de parmesan.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
    ingredients: [
      "400g de filet de bœuf (congélé 2h pour faciliter le tranchage)",
      "60g de parmesan en copeaux",
      "Jus de 2 citrons",
      "4 cuillères à soupe d'huile d'olive extra vierge",
      "Roquette",
      "Sel et poivre du moulin",
    ],
    etapes: [
      "Trancher le filet de bœuf très finement à l'aide d'un couteau bien aiguisé.",
      "Disposer les tranches en rosace sur les assiettes.",
      "Préparer la vinaigrette avec huile d'olive et jus de citron.",
      "Arroser le carpaccio de vinaigrette.",
      "Disposer les copeaux de parmesan et la roquette.",
      "Assaisonner de sel et de poivre fraîchement moulu.",
    ],
  },
  {
    id: 12,
    slug: "cannoli-siciliani",
    nom: "Cannoli Siciliani",
    categorie: "dolce",
    difficulte: "difficile",
    temps: 75,
    portions: 12,
    description: "Les tubes croustillants siciliens fourrés de ricotta sucrée et de pépites de chocolat.",
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&q=80",
    ingredients: [
      "250g de farine",
      "30g de sucre",
      "30g de beurre",
      "1 œuf",
      "60ml de Marsala",
      "500g de ricotta di pecora",
      "150g de sucre glace",
      "100g de pépites de chocolat noir",
      "Huile pour friture",
    ],
    etapes: [
      "Mélanger farine, sucre, beurre, œuf et Marsala. Pétrir et réfrigérer 30 min.",
      "Étaler finement la pâte et couper des disques de 10cm.",
      "Enrouler autour de tubes métalliques et sceller avec de l'œuf.",
      "Frire à 180°C jusqu'à dorure. Laisser refroidir avant de retirer les tubes.",
      "Mixer la ricotta avec le sucre glace jusqu'à obtenir une crème lisse.",
      "Incorporer les pépites de chocolat et garnir les tubes à la poche à douille.",
    ],
  },
];

export default recettes;

// Retourne une recette par son slug, ou null si introuvable
export function getRecetteBySlug(slug) {
  return recettes.find((r) => r.slug === slug) ?? null;
}

// Retourne tous les slugs (utilisé par generateStaticParams)
export function getAllSlugs() {
  return recettes.map((r) => r.slug);
}
